apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-api
  namespace: pong
spec:
  template:
    spec:
      containers:
        - name: api
          args:
            - --mode=lobby
            - --namespace=pong
            - --room-image=ghcr.io/macel94/cloudnativepong-room@sha256:04d8779641169d415f95fa171a6d6570c1d2d8af54ade0f6b56297cde11bf291
            - --db-path=/data/pong.db
          env:
            - name: PONG_ALLOWED_ORIGINS
              value: https://pong.belacca.com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pong-api-data
  namespace: pong
spec:
  resources:
    requests:
      storage: 1Gi