apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-api
  namespace: pong
spec:
  template:
    spec:
      containers:
        - name: api
          args:
            - --mode=lobby
            - --namespace=pong
            - --room-image=ghcr.io/macel94/cloudnativepong-room:sha-0f604a9bc390ab171fafcdfa63c7d041b59e8da1
            - --db-path=/data/pong.db
          env:
            - name: PONG_ALLOWED_ORIGINS
              value: https://pong.belacca.com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pong-api-data
  namespace: pong
spec:
  resources:
    requests:
      storage: 1Gi