apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-api
  namespace: pong
spec:
  template:
    spec:
      containers:
        - name: api
          args:
            - --mode=lobby
            - --namespace=pong
            - --room-image=ghcr.io/macel94/cloudnativepong-room@sha256:f9ace803de8413113bd52ab86f833bb262664f3db190fe0eb3853455d478eca9
            - --db-path=/data/pong.db
          env:
            - name: PONG_ALLOWED_ORIGINS
              value: https://pong.belacca.com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pong-api-data
  namespace: pong
spec:
  resources:
    requests:
      storage: 1Gi