apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pong-gateway
  namespace: pong
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pong-gateway
  minReplicas: 2
  maxReplicas: 4
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
    scaleDown:
      stabilizationWindowSeconds: 300
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pong-static
  namespace: pong
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pong-static
  minReplicas: 2
  maxReplicas: 4
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
    scaleDown:
      stabilizationWindowSeconds: 300
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
