apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pong

resources:
  - ../../base
  - ingress.yaml
  - resource-quota.yaml
  - hpa.yaml

images:
  - name: cloudnativepong-api
    newName: ghcr.io/macel94/cloudnativepong-api
    newTag: sha-a6bef0498bde6454c1b20ba054f0aa973e26c6df
  - name: cloudnativepong-room
    newName: ghcr.io/macel94/cloudnativepong-room
    newTag: sha-a6bef0498bde6454c1b20ba054f0aa973e26c6df
  - name: cloudnativepong-static
    newName: ghcr.io/macel94/cloudnativepong-static
    newTag: sha-a6bef0498bde6454c1b20ba054f0aa973e26c6df
  - name: cloudnativepong-gateway
    newName: ghcr.io/macel94/cloudnativepong-gateway
    newTag: sha-a6bef0498bde6454c1b20ba054f0aa973e26c6df

patches:
  - path: deployment-pull-policy.yaml
  - path: api-recreate-strategy.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: pong-api
      namespace: pong
  - path: api-production.yaml
  - path: room-template.yaml
  - path: stateless-replicas.yaml
