apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pong

resources:
  - ../../base
  - resource-quota.yaml
  - hpa.yaml
  - capacity-alerts.yaml

images:
  - name: cloudnativepong-api
    newName: ghcr.io/macel94/cloudnativepong-api
    newTag: sha-d0896f74cba4c81297b12e60cb933e820766b5f0
  - name: cloudnativepong-room
    newName: ghcr.io/macel94/cloudnativepong-room
    newTag: sha-d0896f74cba4c81297b12e60cb933e820766b5f0
  - name: cloudnativepong-static
    newName: ghcr.io/macel94/cloudnativepong-static
    newTag: sha-d0896f74cba4c81297b12e60cb933e820766b5f0
  - name: cloudnativepong-gateway
    newName: ghcr.io/macel94/cloudnativepong-gateway
    newTag: sha-d0896f74cba4c81297b12e60cb933e820766b5f0

patches:
  - path: deployment-pull-policy.yaml
  - path: api-resources.yaml
  - path: api-recreate-strategy.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: pong-api
      namespace: pong
  - path: api-production.yaml
  - path: room-template.yaml
  - path: stateless-replicas.yaml
