apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pong

resources:
  - ../../base
  - resource-quota.yaml
  - hpa.yaml
  - capacity-alerts.yaml

images:
  - name: cloudnativepong-api
    newName: ghcr.io/macel94/cloudnativepong-api
    digest: sha256:027ebb28eeb0dff69111a9c17cad7c5cddb6e9b096dd7633ba15a9659e238529
  - name: cloudnativepong-room
    newName: ghcr.io/macel94/cloudnativepong-room
    digest: sha256:e133bc420f3d8f0a2beaa553d3754d99e525f4976e1bc18e35f92f160510a39d
  - name: cloudnativepong-static
    newName: ghcr.io/macel94/cloudnativepong-static
    digest: sha256:362cfc8771dd4d8700dd2c2a7c2fa957a9d53413bc12c2156bf3029a005e5389
  - name: cloudnativepong-gateway
    newName: ghcr.io/macel94/cloudnativepong-gateway
    digest: sha256:58940b237c40a0a8afc0c82a096b9db9505093a101830b27e770675041754a15

patches:
  - path: deployment-pull-policy.yaml
  - path: api-resources.yaml
  - path: api-recreate-strategy.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: pong-api
      namespace: pong
  - path: api-production.yaml
  - path: room-template.yaml
  - path: stateless-replicas.yaml
