apiVersion: v1
kind: ResourceQuota
metadata:
  name: pong-capacity
  namespace: pong
spec:
  hard:
    requests.cpu: "12"
    requests.memory: 8Gi
    limits.memory: 12Gi
    pods: "120"
    services: "120"
