apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-gateway
  namespace: pong
spec:
  replicas: 2
  template:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: cloudnativepong
              component: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-static
  namespace: pong
spec:
  replicas: 2
  template:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: cloudnativepong
              component: static
