apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: headlamp-read-only
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - endpoints
      - events
      - namespaces
      - nodes
      - persistentvolumeclaims
      - pods
      - pods/log
      - replicationcontrollers
      - resourcequotas
      - services
      - serviceaccounts
    verbs: [get, list, watch]
  - apiGroups: ["apps"]
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs: [get, list, watch]
  - apiGroups: ["batch"]
    resources:
      - cronjobs
      - jobs
    verbs: [get, list, watch]
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: [get, list, watch]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
      - networkpolicies
    verbs: [get, list, watch]
  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
    verbs: [get, list, watch]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterrolebindings
      - clusterroles
      - rolebindings
      - roles
    verbs: [get, list, watch]
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: ["*"]
    verbs: [get, list, watch]
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: ["*"]
    verbs: [get, list, watch]
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: ["*"]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: headlamp-service-account-reader
  namespace: headlamp
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: headlamp-service-account-reader
  namespace: headlamp
subjects:
  - kind: ServiceAccount
    name: headlamp
    namespace: headlamp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: headlamp-service-account-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp-read-only
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: headlamp-read-only
subjects:
  - kind: ServiceAccount
    name: headlamp
    namespace: headlamp
