apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    deployment:
      replicas: 1
    persistence:
      enabled: true
      existingClaim: traefik-acme
      path: /data
    certificatesResolvers:
      letsencrypt:
        acme:
          email: francesco.belacca@hotmail.it
          storage: /data/acme.json
          httpChallenge:
            entryPoint: web
    additionalArguments:
      - --entryPoints.web.http.redirections.entryPoint.to=:443
      - --entryPoints.web.http.redirections.entryPoint.scheme=https
      - --entryPoints.web.http.redirections.entryPoint.permanent=true
