#!/usr/bin/env bash
# Verify GitHub Artifact Attestation provenance for one immutable Pong image.
# The attestation is generated by the repository's publish-images workflow and
# pushed to GHCR by actions/attest; no separate signing CLI or key is required.
# Verification uses GitHub's attestation API, which also works when the OCI
# registry does not expose referrers anonymously.
set -euo pipefail

usage() {
  echo "usage: $0 ghcr.io/macel94/cloudnativepong-<component>@sha256:<64-hex-digest> [--dry-run]" >&2
  exit 2
}

image="${1:-}"
dry_run=0
if [[ "${2:-}" == --dry-run ]]; then
  dry_run=1
elif [[ $# -gt 1 ]]; then
  usage
fi

[[ "$image" =~ ^ghcr\.io/macel94/cloudnativepong-(api|room|static|gateway)@sha256:[0-9a-f]{64}$ ]] || {
  echo 'an exact immutable Pong IMAGE@sha256:<64-hex-digest> is required' >&2
  exit 2
}

args=(
  "oci://$image"
  --repo macel94/cloudnativepong
  --signer-workflow macel94/cloudnativepong/.github/workflows/publish-images.yml
  --predicate-type https://slsa.dev/provenance/v1
)

if ((dry_run)); then
  printf 'would run: gh attestation verify'
  printf ' %q' "${args[@]}"
  printf '\n'
  echo 'requires GitHub CLI authentication and a published GHCR attestation'
  exit 0
fi

command -v gh >/dev/null 2>&1 || {
  echo 'gh (GitHub CLI) is required; install it or use --dry-run' >&2
  exit 127
}

exec gh attestation verify "${args[@]}"
