apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-api
  namespace: pong
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: api
          imagePullPolicy: Always
          args:
            - --mode=lobby
            - --namespace=pong
            - --room-image=ghcr.io/macel94/cloudnativepong-room:sha-98f95faa7d2fdd5cc50d1ce6142080da84f04298
            - --db-path=/data/pong.db
          env:
            - name: PONG_ALLOWED_ORIGINS
              value: https://pong.belacca.com
