apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-api
  namespace: pong
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: api
          imagePullPolicy: Always
          args:
            - --mode=lobby
            - --namespace=pong
            - --room-image=ghcr.io/macel94/cloudnativepong-room@sha256:0a724a14d55d3a6cfa0be4b2981bdc4f2392828dff6d4fcc2c64a705591a8c3e
            - --db-path=/data/pong.db
          env:
            - name: PONG_ALLOWED_ORIGINS
              value: https://pong.belacca.com
